server:
  port: 2103
spring:
  data:
    mongodb:
      uris:
        - mongodb://root:password@localhost:27017
operatorfabric.users.default:
  users:
    - login: admin
      groupSet: [ADMIN]
  groups:
    - name: ADMIN
      description: The admin group