version: '2.1'
services:
  config:
    container_name: config
    image: "org.lfenergy.operatorfabric/configuration-cloud-service:latest"
    ports:
     - "2000:8080"
     - "4000:5005"
    expose:
     - "8080"
    volumes:
     - "../../../build/docker-volume:/config"
    networks:
     - opfabnet
networks:
 opfabnet:
   external:
     name: opfabnet
