spring:
  application:
    name: cards-publication
  cloud:
    discovery:
      enabled: false
    config:
      discovery:
        enabled: false
      enabled: false
  data:
    mongodb:
      database: operator-fabric
operatorfabric:
  card-notification.window:
    size: 100
    timeout: 1000