
spring:
  application:
    name: cards-publication


#here we put urls for all feign clients
users:
  ribbon:
    listOfServers: users:8080

externalRecipients-url: "{\
           api_test_externalRecipient1: \"http://localhost:8090/test\", \
           api_test_externalRecipient2: \"http://localhost:8090/test\" \
           }"