
spring:
  application:
    name: cards-publication


#here we put urls for all feign clients
users:
  ribbon:
    listOfServers: users:8080
# WARNING - If you are not working on linux, you should replace the host ip address 172.17.0.1 
# for mac see https://docs.docker.com/docker-for-mac/networking/#use-cases-and-workarounds
# for windows see https://docs.docker.com/docker-for-windows/networking/#use-cases-and-workarounds
externalRecipients-url: "{\
           processAction: \"http://172.17.0.1:8090/test\", \
           api_test_externalRecipient1: \"http://172.17.0.1:8090/test\", \
           api_test_externalRecipient2: \"http://172.17.0.1:8090/test\", \
           externalRecipient1: \"http://172.17.0.1:8090/test\", \
           externalRecipient2: \"http://172.17.0.1:8090/test\" \
           }"

# WARNING : If you set this parameter to false , all users have the rights to respond to all cards
checkPerimeterForResponseCard: true
