version: '2.1'
services:
  mongodb:
    image: mongo:4.1.1-xenial
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
  keycloak:
    image: jboss/keycloak:6.0.1
    command: -Dkeycloak.migration.action=import -Dkeycloak.migration.provider=dir -Dkeycloak.migration.dir=/keycloak/export
    environment:
    - KEYCLOAK_USER=admin
    - KEYCLOAK_PASSWORD=admin
    - DB_VENDOR=H2
    volumes:
    - ../keycloak:/keycloak
    ports:
    - "89:8080"
    - "90:9990"
  users:
    container_name: users
    image: "lfeoperatorfabric/of-users-business-service:SNAPSHOT"
    user: ${USER_ID}:${USER_GID}
    ports:
     - "2103:8080"
     - "4103:5005"
    volumes:
    - "../certificates:/certificates_to_add"
    - "./users-docker.yml:/config/application.yml"
    - "./common-docker.yml:/config/common-docker.yml"
  businessconfig:
    container_name: businessconfig
    image: "lfeoperatorfabric/of-businessconfig-business-service:SNAPSHOT"
    depends_on:
      - mongodb
    user: ${USER_ID}:${USER_GID}
    ports:
     - "2100:8080"
     - "4100:5005"
    volumes:
     - "../certificates:/certificates_to_add"
     - "../../services/core/businessconfig/src/main/docker/volume/businessconfig-storage:/businessconfig-storage"
     - "./common-docker.yml:/config/common-docker.yml"
     - "./businessconfig-docker.yml:/config/application-docker.yml"
  cards-publication:
    container_name: cards-publication
    image: "lfeoperatorfabric/of-cards-publication-business-service:SNAPSHOT"
    depends_on:
      - mongodb
    user: ${USER_ID}:${USER_GID}
    ports:
     - "2102:8080"
     - "4102:5005"
    volumes:
      - "../certificates:/certificates_to_add"
      - "./common-docker.yml:/config/common-docker.yml"
      - "./cards-publication-docker.yml:/config/application-docker.yml"
  cards-consultation:
    container_name: cards-consultation
    image: "lfeoperatorfabric/of-cards-consultation-business-service:SNAPSHOT"
    user: ${USER_ID}:${USER_GID}
    ports:
     - "2104:8080"
     - "4104:5005"
    volumes:
      - "../certificates:/certificates_to_add"
      - "./common-docker.yml:/config/common-docker.yml"
      - "./cards-consultation-docker.yml:/config/application-docker.yml"
  web-ui:
    image: "lfeoperatorfabric/of-web-ui:SNAPSHOT"
    ports:
    - "2002:80"
    depends_on:
      - users
      - businessconfig
      - cards-consultation
    volumes:
      - "./web-ui.json:/usr/share/nginx/html/opfab/web-ui.json"
      - "./ngnix.conf:/etc/nginx/conf.d/default.conf"
