version: '2.1'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
  operatorfabric.thirds:
    depends_on:
      - "rabbitmq"
    image: "org.lfenergy.operatorfabric/config"
    ports:
     - "2000:8080"
     - "3100:5005"
    volumes:
     - "../../../services/core/thirds/build/docker-volume:/configuration"
  operatorfabric.thirds:
    depends_on:
      - "rabbitmq"
    image: "org.lfenergy.operatorfabric/thirds"
    ports:
     - "2100:8080"
     - "3100:5005"
    volumes:
     - "../../../services/core/thirds/build/docker-volume:/configuration"
  time:
    depends_on:
      - "rabbitmq"
    image: "org.lfenergy.operatorfabric/time"
    ports:
     - "2101:8080"
     - "3101:5005"
    volumes:
     - "../../../services/core/time/build/docker-volume:/configuration"