server:
  port: 2103
operatorfabric.users.default:
  users:
    - login: admin
      groups: ["ADMIN"]
    - login: rte-operator
      groups: ["RTE","ADMIN","TRANS"]
    - login: tso1-operator
      groups: ["TSO1","TRANS"]
    - login: tso2-operator
      groups: ["TSO2", "TRANS"]
  groups:
    - name: ADMIN
      description: The admin group
    - name: RTE
      description: RTE TSO Group
    - name: TSO1
      description: TSO 1 Group
    - name: TSO2
      description: TSO 2 Group
    - name: TRANS
      description: Transnationnal Group
  user-settings:
    - login: rte-operator
      description: Da Operator Rulez
operatorfabric:
  security:
    jwt:      
      groups:
        mode: JWT # value possible JWT | OPERATOR_FABRIC
        rolesClaim:
         - path: eicCode
           singleValue: true
           mandatory: true
         - path: resource_access/opfab-client/roles
           singleValue: false
           separator: ","
           mandatory: true
         - path: "resource_access/STA"
           mandatory: false  
         - path: "resource_access/OPC"
           mandatory: false    
#logging.level.root: DEBUG