spring:
  cloud:
    gateway:
      globalcors:
        # WARNING : THIS CORS CONFIGURATION SHOULD NOT BE USED IN PRODUCTION
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "Authorization, Content-Type"
      routes:
      - id: auth
        uri: http://keycloak:8080
        predicates:
        - Path=/auth/**
        filters:
        - RewritePath=/auth/token(?<path>.*), /auth/realms/dev/protocol/openid-connect/token$\{path}
        - RewritePath=/auth/code/(?<params>.*), /auth/realms/dev/protocol/openid-connect/auth?response_type=code&client_id=opfab-client&$\{params}
        - RewritePath=/auth/check_token, /auth/realms/dev/protocol/openid-connect/token/introspect
        - AddRequestHeader=Authorization, Basic b3BmYWItY2xpZW50Om9wZmFiLWtleWNsb2FrLXNlY3JldA==
      - id: actions
        uri: http://actions:2105
        predicates:
          - Path=/actions/**
        filters:
          - RewritePath=/actions/(?<path>.*), /$\{path}
      - id: web-ui
        uri: http://web-ui:80
        predicates:
          - Path=/ui/**
        filters:
          - RewritePath=/ui/(?<path>.*), /$\{path}
      - id: thirds
        uri: http://thirds:2100
        predicates:
          - Path=/thirds/**
        filters:
          - RewritePath=/thirds/(?<path>.*), /thirds/$\{path}
      - id: cards
        uri: http://cards-consultation:2104
        predicates:
          - Path=/cards/**
        filters:
          - RewritePath=/cards/(?<path>.*), /$\{path}
      - id: archives
        uri: http://cards-consultation:2104
        predicates:
          - Path=/archives/**
        filters:
          - RewritePath=/archives/(?<path>.*), /$\{path}
      - id: users
        uri: http://users:8080
        predicates:
          - Path=/users/**
        filters:
          - RewritePath=/users/(?<path>.*), /$\{path}
operatorfabric.gateway.configs:
  - web-ui.json
