operatorfabric.users.default:
  users:
  - login: admin
    groups: ["ADMIN"]
    entities: ["ENTITY1","ENTITY2"]
  - login: rte-operator
    groups: ["RTE","ADMIN","TRANS"]
  - login: tso1-operator
    groups: ["TSO1","TRANS"]
    entities: ["ENTITY1"]
  - login: tso2-operator
    groups: ["TSO2", "TRANS"]
    entities: ["ENTITY2"]
  groups:
  - name: ADMIN
    description: The admin group
  - name: RTE
    description: RTE TSO Group
  - name: TSO1
    description: TSO 1 Group
  - name: TSO2
    description: TSO 2 Group
  - name: TRANS
    description: Transnationnal Group
  entities:
  - id: ENTITY1
    name: Entity 1 name
    description: Entity 1 short description
  - id: ENTITY2
    name: Entity 2 name
    description: Entity 2 short description