server:
  port: 2105
spring:
  application:
    name: actions

operatorfabric:
  services:
    base-url:
      cards: http://localhost:2104
      thirds: http://localhost:2100
      users: http://localhost:2103
