server:
  port: 2102
spring:
  application:
    name: cards-publication
  kafka:
    consumer:
      #Uncomment the Kafka group-id to enable Kafka
#      group-id: opfab-command
      auto-offset-reset: earliest
  deserializer:
    key:
      delegate:
        class: org.apache.kafka.common.serialization.StringDeserializer
    value:
      delegate:
        class: org.lfenergy.operatorfabric.cards.publication.kafka.consumer.CardCommandConsumerDeserializer

#here we put urls for all feign clients
users:
  ribbon:
    listOfServers: http://localhost:2103

externalRecipients-url: "{\
           processAction: \"http://localhost:8090/test\", \
           api_test_externalRecipient1: \"http://localhost:8090/test\", \
           api_test_externalRecipient2: \"http://localhost:8090/test\" \
           }"
