server:
  port: 2102
spring:
  application:
    name: cards-publication

#here we put urls for all feign clients
users:
  ribbon:
    listOfServers: http://localhost:2103

externalRecipients-url: "{\
           api_test_externalRecipient1: \"http://localhost:8090/test\", \
           api_test_externalRecipient2: \"http://localhost:8090/test\" \
           }"
