spring:
  kafka:
    consumer:
      group-id: smt01
      value-deserializer: org.lfenergy.operatorfabric.cards.publication.kafka.consumer.CardCommandConsumerDeserializer
      auto-offset-reset: earliest
#    listener:
#      concurrency: 1
#      poll-timeout: 2000
