server:
  port: 2100
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:89/auth/realms/dev/protocol/openid-connect/certs

operatorfabric.thirds:
  storage:
    path: "./services/core/thirds/build/docker-volume/thirds-storage"

#here we put urls for all feign clients
users:
  ribbon:
    listOfServers: http://localhost:2103
